"""
PipelineState — the shared LangGraph state object.

This is passed into every node and returned (partially updated) by each one.
LangGraph merges returned dicts back into the state automatically.

Design rule: nodes READ anything they need, WRITE only their own output fields.
  - fix_node      → writes: fixes, fix_log
  - summary_node  → writes: summary_report
  - sbom_node     → writes: sbom_optimization_report
"""

from typing import Optional, Annotated
from pydantic import BaseModel, Field
from langgraph.graph.message import add_messages

from schemas.vulnerability import Vulnerability
from schemas.sbom import SBOM


class FixSuggestion(BaseModel):
    """A single fix suggestion produced by the Security Fixing Agent."""

    vulnerability_id: str = Field(
        description="The vuln ID this fix addresses."
    )
    package_name: Optional[str] = Field(
        default=None,
        description="Package to be updated, if applicable."
    )
    current_version: Optional[str] = Field(
        default=None,
        description="Currently installed version."
    )
    suggested_version: Optional[str] = Field(
        default=None,
        description="Version to upgrade to."
    )
    fix_type: str = Field(
        description=(
            "Category of fix. One of: "
            "'dependency_upgrade', 'base_image_pin', "
            "'non_root_user', 'multi_stage_build', 'manual_review'"
        )
    )
    description: str = Field(
        description="Human-readable explanation of what to change and why."
    )
    safe_to_automate: bool = Field(
        default=False,
        description="True only for deterministic fixes like version pinning. Never True for logic changes."
    )


class PipelineState(BaseModel):
    """
    Shared state object passed between all LangGraph nodes.

    Populated progressively as the pipeline executes:
      1. Initialized with scanner outputs before the graph runs.
      2. fix_node adds fixes + fix_log.
      3. summary_node adds summary_report.
      4. sbom_node adds sbom_optimization_report.
    """

    # --- Inputs: populated before graph execution ---
    vulnerabilities: list[Vulnerability] = Field(
        default_factory=list,
        description="All normalized vulnerabilities from all scanners."
    )
    sbom: Optional[SBOM] = Field(
        default=None,
        description="Parsed SBOM from Syft."
    )
    dockerfile_content: Optional[str] = Field(
        default=None,
        description="Raw Dockerfile content of the target repo, for fix analysis."
    )
    target_repo: Optional[str] = Field(
        default=None,
        description="Name of the repository being scanned. E.g. 'org/vulnerable-repo'."
    )

    # --- Output: Security Fixing Agent ---
    fixes: list[FixSuggestion] = Field(
        default_factory=list,
        description="Fix suggestions generated by the fixing agent."
    )
    fix_log: list[str] = Field(
        default_factory=list,
        description="Audit log of fix agent reasoning steps."
    )

    # --- Output: Summarization Agent ---
    summary_report: Optional[str] = Field(
        default=None,
        description="Markdown security summary report produced by the summary agent."
    )

    # --- Output: SBOM Optimization Agent ---
    sbom_optimization_report: Optional[str] = Field(
        default=None,
        description="Markdown SBOM optimization report produced by the SBOM agent."
    )

    # --- Pipeline metadata ---
    errors: list[str] = Field(
        default_factory=list,
        description="Any non-fatal errors encountered during parsing or agent execution."
    )

    class Config:
        use_enum_values = True